"""Add user default fully_invested

Revision ID: 063c5112ae67
Revises: 52829127de11
Create Date: 2023-07-12 20:17:46.784873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063c5112ae67'
down_revision = '52829127de11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fully_invested', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('fully_invested')

    # ### end Alembic commands ###
